name: first workflow

on: 
 issues:
 push:
 workflow_dispatch:

jobs:
 job1:
  runs-on: ubuntu-latest
  steps:
   - run: echo 'Hello for ubuntu'
 job2:
  needs: job1
  runs-on: windows-latest
  steps:
   - run: echo 'Hello for Windows'
